---
services:
  nexus:
    image: sonatype/nexus3@sha256:80b945be128a6466320df09589d73ed4a5dbf09f3495243281d264bbc643228c
    container_name: nexus
    restart: unless-stopped
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - /docker/appdata/nexus:/nexus-data
