---
services:
  nexus:
    image: docker.mafyuh.xyz/sonatype/nexus3:3.69.0
    container_name: nexus
    restart: unless-stopped
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - /docker/appdata/nexus:/nexus-data ## Need to run sudo chown -R 200 /docker/appdata/nexus/ for this to work
