---
services:
  nexus:
    image: sonatype/nexus3@sha256:6f76093012851c9404265b66ea490df137d9dc274adce100421d3a33f901f1d5
    container_name: nexus
    restart: unless-stopped
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - /docker/appdata/nexus:/nexus-data
