---
services:
  nexus:
    image: docker.mafyuh.xyz/sonatype/nexus3@sha256:d4c592b2c1ca48273163e3e29e6272bb4607c3b0c5c199e23d170322b65dfe70
    container_name: nexus
    restart: unless-stopped
    ports:
      - 8081:8081
      - 8082:8082
    volumes:
      - /docker/appdata/nexus:/nexus-data
