---
kind: pipeline
type: docker
name: lint-docker-compose

trigger:
  event:
    - push
    - pull_request

platform:
  os: linux
  arch: amd64

steps:
  - name: lint-docker-compose
    image: docker/compose:1.29.2
    commands:
      - docker-compose -f docker-compose.yml config
