kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - tag

platform:
  os: linux
  arch: amd64

steps:
  - name: update-docker-images
    image: docker
    commands:
      - docker-compose pull
      - docker-compose up -d --remove-orphans
