kind: pipeline
name: lint

steps:
- name: lint-docker-compose
  image: docker/compose:1.29.2
  commands:
    - docker-compose -f docker-compose.yml config --quiet
    - docker-compose -f docker-compose.yml config
