kind: pipeline
name: lint

steps:
{{#each services}}
- name: lint-${{ normalize . }}
  image: docker/compose:1.29.2
  commands:
    - cd ./${{ normalize . }}
    - docker-compose config --quiet
    - docker-compose config
{{/each}}
