version: "3.7"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr@sha256:0675b882e5a0cc4ab1b7c97d6374bc54228115711dc756f3259b4b3e86120dc8
    ports:
      - "6767:6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/bazarr:/config
      - /data/media:/data/media
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0

  lidarr:
    image: lscr.io/linuxserver/lidarr@sha256:d2da8fc4e16f7e9c430a7232da5eb4ce345dad50524d818b651ddafd14d337be
    ports:
      - "8686:8686"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/lidarr:/config
      - /data:/data
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

  prowlarr:
    image: lscr.io/linuxserver/prowlarr@sha256:d5827afd8ddcfe1cc13efd71a35ccefe1d11de37e88cd2f81c82149b3e100964
    ports:
      - "9696:9696"
    volumes:
      - /docker/appdata/prowlarr:/config
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

  radarr:
    image: lscr.io/linuxserver/radarr@sha256:1ddfb42f3765b46d9b380d07aa053d565126c114d5f6f8ba304a5d6e2454b115
    ports:
      - "7878:7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/radarr:/config
      - /data:/data
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

  sonarr:
    image: lscr.io/linuxserver/sonarr@sha256:5719c66eeca417838eb509a4fb66e7ae5897b84a5bd01ba6e27057b292698218
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/appdata/sonarr:/config
      - /data:/data
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000

networks:
  default:
    name: arrs_default