name: 'Delete Application'
description: 'Track the process of deleting an application'
title: 'Delete Application: [Application Name]'
labels: 
  - deletion
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        ## Application Details

  - type: input
    id: application-name
    attributes:
      label: Application Name
      description: Name of the application to be deleted
      placeholder: Name of the application

  - type: checkboxes
    id: reason-for-deletion
    attributes:
      label: Reason for Deletion
      description: Please select one or more reasons for the deletion
      options:
        - label: No longer needed
        - label: Replaced by another application
          description: Provide the name of the new application, if applicable
        - label: Maintenance overhead
        - label: Security vulnerabilities
        - label: Performance issues
        - label: Compatibility issues
        - label: Licensing issues
        - label: Other (please specify)
          description: Provide additional details

  - type: checkboxes
    id: impacted-folders
    attributes:
      label: Impacted Folders
      description: Select the folders that are impacted by the deletion
      options:
        - label: ag-backup
        - label: ag-main
        - label: AI
        - label: arm
        - label: arrs
        - label: authentik
        - label: cf
        - label: downloaders
        - label: jellyfin
        - label: kasm
        - label: netboot
        - label: nexus
        - label: pages
        - label: portainer
        - label: twingate
        - label: whisper

  - type: markdown
    attributes:
      value: |
        ## Steps to Delete

  - type: checkboxes
    id: steps-to-delete
    attributes:
      label: Steps to Delete
      description: Please check off each step as it is completed
      options:
        - label: Remove Configuration Files
          description: Locate and remove all configuration files related to the application
        - label: Update Wiki
          description: Add Archived tag to Wiki page and update any architecture diagrams or flowcharts
        - label: Update README(s)
          description: Remove app from main table
        - label: Remove From CD Platform Logic
          description: Remove unneeded if statement from CD platform
        - label: Deletion from host
          description: Ensure that the application and all related files have been successfully removed
        - label: Close Related Issues
          description: Close any open issues or tasks related to the application
        - label: If you are deleting the entire folder check this box
          description: Deleting entire folder

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any additional comments or details here
      placeholder: Comments
