---
services:
  cf-tunnel:
    restart: unless-stopped
    image: docker.mafyuh.xyz/cloudflare/cloudflared@sha256:f6e9fff347602b8e70f1765127abc96f3b8d1af4cc46185913a043edab75ae5b
    command: tunnel --no-autoupdate run --token $CF_TOKEN
