---
services:
  cf-tunnel:
    image: docker.mafyuh.xyz/cloudflare/cloudflared@sha256:9eb8554739a1d6b4d63091f7b724cbd9bb39b8c0c23e38200a9e7ad86ccc67cd
    command: tunnel --no-autoupdate run --token $CF_TOKEN
