---
services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz@sha256:ebeab68106c582d0926fe2a3fffcd2f1fae3864116771ecb5af7a2d370153db5
    container_name: netboot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/mafyuh/netboot/config:/config
      - /home/mafyuh/netboot/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped
