---
services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz@sha256:4a0570dbc6128fae6db3366b52310e4ed6394e68e5183dbf9c18e1055c3058f3
    container_name: netboot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/mafyuh/netboot/config:/config
      - /home/mafyuh/netboot/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped
