---
services:
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz@sha256:b1fb54be7e3f274b4a488eb2a8565e541ca4f105228028dd0afbb3ce8614810a
    container_name: netboot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/mafyuh/netboot/config:/config
      - /home/mafyuh/netboot/assets:/assets
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80
    restart: unless-stopped
